Finish the documentation required by the repo merge
Mesnage-Org/pgfinder pull request #237
Opened 2023-09-09 13:37 UTC by TheLostLambda

2023-09-09 14:56 UTC, TheLostLambda commented
Ready for @ns-rse and @bobturneruk to take a look at! It would be good if you could test the contributing instructions and see if you can get the Svelte application up and running!

2023-09-09 15:21 UTC, TheLostLambda commented
I'm happy ignoring that Codacy check, since the README was already without indents for the list items — I just happened to reword something on the same line.

2023-09-11 09:38 UTC, ns-rse requested changes
Good work going through all these tweaks and updates and addition of section on the web-framework contributions is really useful (for me too!).

One minor suggestion on wording as not all `pre-commit` tests will fail.

2023-09-11 09:38 UTC, ns-rse commented on lib/docs/contributing.md
> +if you have not run them locally, then your pull request will fail the tests it needs to pass.
Minor but its not guaranteed that the tests on CI will fail.

```suggestion
if you have not run them locally, then your pull request may fail the tests it needs to pass.
```

2023-09-11 12:42 UTC, ns-rse approved these changes
Thanks for addressing so quickly, looks good to go.

2023-09-11 15:34 UTC, merged