9 | Adding find_pg.py a command line script
Mesnage-Org/pgfinder pull request #75
Opened 2022-05-13 16:32 UTC by ns-rse

This creates the `find_pg.py` script which works with the `config/example.yaml` sample configuration file to run pgfinder at the command line. The `README.md` includes and example of how to use this and configuration options in the file can be over-written at run-time using command line options.

Currently I've not changed much in `setup.py` as I will likely switch to `setup.cfg` and `pyproject.toml` as I work towards making this a package and releasing it to PyPi so you may find you need to install at the very least `ruamel.yaml`. In your virtualenv...

```bash
pip install ruamel.yaml
```

2022-05-20 10:54 UTC, ns-rse commented
> Line 190 has a codecov comment - not covered in test. Would be good to add the unit test for this before merging in. Otherwise looks good to me!

Thanks @Ankur-AVP-Patel the change I made here just switches to using the `pathlib` module for creating the filepath, so the lack of unit-test for saving the CSV already existed.

Unittests are covered by issue #3 and there are quite a few highlighted by the Code Coverage report, so I'd like to keep introduction of tests to a separate branch/task as I go through the various issues if that's ok.

2022-05-23 13:21 UTC, bobturneruk requested changes
I like this. Some points around the CLI invocation that I think need attention, and I think it would be fine to use this opportunity to harmonise `setup.py`, `setup.cfg` and `pyproject.toml`, but I leave that up to you. Cheers!

2022-05-23 13:31 UTC, ns-rse commented on pgfinder/io.py
> +"""Functions for reading and writing data."""
Sure,  copied an existing `io.py` from elsewhere and added it, now under `pgio.py`.

2022-05-23 13:32 UTC, ns-rse commented on config/parameters.json
> +// Multimer type
No, but since I pulled the data out to JSON I thought it worth including rather than leaving it lying around on my computer.

2022-05-23 13:40 UTC, ns-rse commented on setup.cfg
> +install_requires =
I think `setuptools` is moving away from `setup.py` towards `setup.cfg` / `pyproject.toml` as described in [this page](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setup-py). Retaining `setup.py` does seem to provide some functionality if _custom scripting is required during build_, which I don't think it is here. I'll therefore aim to remove `setup.py` in favour of `setup.cfg`/`pyproject.toml`.

2022-05-23 14:00 UTC, bobturneruk commented on setup.cfg
> +install_requires =
Fine by me.

2022-05-23 14:54 UTC, ns-rse commented on README.md
> +python find_pg.py -c config/example.py
Hopefully installs now though, its listed in `setup.cfg`.

2022-05-24 10:01 UTC, Ankur-AVP-Patel approved these changes

2022-05-24 10:19 UTC, ns-rse commented
Thanks for the approval @Ankur-AVP-Patel :+1:

2022-05-25 09:50 UTC, bobturneruk approved these changes
Couple of specific comments in there. The CLI won't work on windows but let's fix that later. Also - do we still need `io.py` or is it all in `pgio.py`?

2022-05-25 09:50 UTC, bobturneruk commented on README.md
> +./find_pg.py -c config/example.yaml
```suggestion
./find_pg -c config/example.yaml
```

2022-05-25 09:50 UTC, bobturneruk commented on README.md
> +./find_pg.py -c config/example.yaml
This won't work on Windows - maybe put a note to this effect. We can address later.

2022-05-25 09:50 UTC, bobturneruk commented on .github/workflows/ci-tests.yml
>            pip install -e .
Line 24 probably not needed.

2022-05-25 10:08 UTC, merged